describe('Places app login and logout test', function() {
    it('Login for can be opened', function() {   
        let url = Cypress.env('URL')
        cy.visit(url)
        cy.get('div[id="login"]').click()
        cy.contains('Username')
        cy.contains('Password')
        cy.get('input[id="userName"]').type('E')
        cy.get('input[id="password"]').type(1)
        cy.get('button').contains('Login').click()
        cy.contains('E')
        cy.contains('Place name')
        cy.get('div[id="login"]').click()
    })
})